import { providerFetch } from "@/lib/providers";
import type { Drama, Episode } from "@/lib/dramas";
import { preferredRoutes, type ProviderMode } from "@/lib/provider-routes";

type Rec = Record<string, any>;
type Param = { name:string; in:string; required:boolean; defaultValue?:string };
type Op = { method:string; route:string; provider:string; summary:string; operationId:string; parameters:Param[] };

export const CAPTAIN_PROVIDERS = [
  "Anichin","BiliTV","BonusTV","CashDrama","CubeTV","DotDrama","DramaBite","DramaBox Baru","DramaNova","DramaPops","DramaRush","FlareFlow","FlexTV","FlickReels","FreeReels","LuminaReels","MeloShort","Melolo","MicroDrama","MoboReels","MovieBox","NetShort","Playlet","RadReels","RapidTV","RaptDrama","ReelBuzz","ReelShort","Sereal","ShortBox","ShortMax","ShortSky","ShortWave","Shorten","ShotShort","SnackShort","SodaReels","StarShort","StardustTV","Vigloo","WeTV","iDrama"
] as const;

export function providerSlug(name:string){return name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
export function providerName(slug:string){return CAPTAIN_PROVIDERS.find((p)=>providerSlug(p)===slug) || null}

const UNSAFE_OPERATION = /unlock|bypass|decrypt|decrypted|terdekripsi|paywall|drm|premium|\bvip\b|berbayar|locked\s*content/i;

let cached:{at:number;ops:Op[]}|null=null;
function embeddedSpec(html:string):Rec|null{for(const marker of["openapi","swagger"]){let cursor=0;while((cursor=html.indexOf(`\"${marker}\"`,cursor))!==-1){const start=html.lastIndexOf("{",cursor);if(start<0)break;let depth=0,quoted=false,escaped=false;for(let i=start;i<html.length;i++){const ch=html[i];if(quoted){if(escaped)escaped=false;else if(ch==="\\")escaped=true;else if(ch==='"')quoted=false;continue}if(ch==='"')quoted=true;else if(ch==="{")depth++;else if(ch==="}"&&--depth===0){try{const parsed=JSON.parse(html.slice(start,i+1));if(parsed?.paths)return parsed}catch{}break}}cursor+=marker.length+2}}return null}
function parameterDefault(p:any):string|undefined{const v=p?.schema?.default ?? p?.example ?? p?.schema?.example;if(v===undefined||v===null||v==="")return undefined;return String(v)}
async function operations():Promise<Op[]>{if(cached&&Date.now()-cached.at<3600000)return cached.ops;let spec:Rec|null=null;for(const path of["/openapi.json","/swagger.json","/swagger/v1/swagger.json","/api-docs"]){try{const r=await providerFetch("captain",path);if(r.ok){const j=await r.json();if(j?.paths){spec=j;break}}}catch{}}if(!spec){const r=await providerFetch("captain","/swagger");if(!r.ok)throw new Error(`Swagger ${r.status}`);spec=embeddedSpec(await r.text())}if(!spec)throw new Error("Captain OpenAPI unavailable");const ops:Op[]=[];for(const[route,item]of Object.entries<any>(spec.paths||{})){for(const method of["get","post"]){const op=item?.[method];if(!op)continue;const summary=op.summary||"",operationId=op.operationId||`${method} ${route}`;if(UNSAFE_OPERATION.test(`${route} ${summary} ${operationId}`))continue;for(const provider of op.tags||[]){ops.push({method:method.toUpperCase(),route,provider,summary,operationId,parameters:[...(item.parameters||[]),...(op.parameters||[])].map((p:any)=>({name:p.name,in:p.in,required:!!p.required,defaultValue:parameterDefault(p)}))})}}}cached={at:Date.now(),ops};return ops}

function rec(v:unknown):v is Rec{return !!v&&typeof v==="object"&&!Array.isArray(v)}
function txt(r:Rec,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==="string"&&v.trim())return v.trim();if(typeof v==="number")return String(v)}return""}
function num(r:Rec,keys:string[]){for(const k of keys){const n=Number(r[k]);if(Number.isFinite(n)&&n>0)return n}return 0}
function rawId(r:Rec){return txt(r,["key","id","drama_id","dramaId","book_id","bookId","series_id","seriesId","series_key","seriesKey","playlet_id","playletId","short_play_id","shortPlayId","videoid","videoId","vid","contentId","subjectId","code","slug"])}
function title(r:Rec){return txt(r,["title","name","drama_name","dramaName","book_name","bookName","book_title","bookTitle","series_name","seriesName","playlet_title","playletTitle","short_play_name","shortPlayName","videoName","contentName"])}
function image(r:Rec,depth=0):string{if(depth>4)return"";const direct=txt(r,["cover","process_cover","cover_url","coverUrl","poster","poster_url","posterUrl","image","image_url","imageUrl","thumb","thumbnail","verticalCover","bookCover","book_pic","bookPic"]);if(/^https?:\/\//i.test(direct))return direct;for(const v of Object.values(r)){if(rec(v)){const x=image(v,depth+1);if(x)return x}}return""}
function looksLikeDrama(r:Rec){if(!rawId(r)||!title(r))return false;const keys=Object.keys(r).join(" ").toLowerCase();if(/language_code|language_name|locale|country_code/.test(keys)&&!/(cover|poster|episode|chapter|playlet|drama|series|book)/.test(keys))return false;return true}
function objects(v:unknown,depth=0):Rec[]{if(depth>7)return[];if(Array.isArray(v)){const d=v.filter(rec).filter(looksLikeDrama);if(d.length)return d;return v.flatMap((x)=>objects(x,depth+1))}if(rec(v)){for(const k of["items","list","lists","data","dramas","results","records","content","rows","videos","books","recommendations","playlets","rank_list"]){if(k in v){const f=objects(v[k],depth+1);if(f.length)return f}}return Object.values(v).flatMap((x)=>objects(x,depth+1))}return[]}
function episodeObjects(v:unknown,depth=0):Rec[]{if(depth>7)return[];if(Array.isArray(v)){const rs=v.filter(rec);const eps=rs.filter((r)=>num(r,["episode","episode_no","episodeNo","episodeNumber","ep","index","chapter","chapter_num","chapterNum","chapterIndex","episodeIndex"])||txt(r,["episodeid","episode_id","episodeId","chapter_id","chapterId","fileId","section_id","sectionId"]));if(eps.length)return eps;return v.flatMap((x)=>episodeObjects(x,depth+1))}if(rec(v)){for(const k of["episodes","episode_list","episodeList","chapters","chapterList","chapter_list","videoList","videos","sections","list","items","data"]){if(k in v){const f=episodeObjects(v[k],depth+1);if(f.length)return f}}return Object.values(v).flatMap((x)=>episodeObjects(x,depth+1))}return[]}
function stream(v:unknown,depth=0):string{if(depth>8)return"";if(typeof v==="string"&&/^https?:\/\//i.test(v)&&/(\.m3u8|\.mp4|stream|video)/i.test(v))return v;if(Array.isArray(v)){for(const x of v){const s=stream(x,depth+1);if(s)return s}}else if(rec(v)){for(const k of["external_audio_h264_m3u8","hls_url","hlsUrl","m3u8_url","m3u8Url","m3u8","video_url","videoUrl","play_url","playUrl","stream_url","streamUrl","url"]){const s=stream(v[k],depth+1);if(s)return s}for(const x of Object.values(v)){const s=stream(x,depth+1);if(s)return s}}return""}

function isBadCatalogOp(op:Op){return /language|languages|locale|locales|config|setting|region|country|category|categories|genre|genres|tag|tags|keyword|suggest|search\/hot|history|vip|subscription|profile|user/i.test(`${op.route} ${op.summary} ${op.operationId}`)}
function canAuto(op:Op,mode:ProviderMode){const req=op.parameters.filter((p)=>p.required&&p.in!=="header");if(mode==="catalog")return req.every((p)=>p.defaultValue!==undefined||/page|offset|limit|size|count|lang|language|country|region|tab/i.test(p.name));if(mode==="detail"||mode==="episodes")return req.length<=4&&req.every((p)=>p.defaultValue!==undefined||/id|code|slug|vid|keyword|content|playlet|series|book|page|season|fake/i.test(p.name));return req.length<=5&&req.every((p)=>p.defaultValue!==undefined||/id|code|slug|vid|ep|episode|chapter|section|content|playlet|series|book|fake/i.test(p.name))}
function score(op:Op,mode:ProviderMode){const s=`${op.route} ${op.summary} ${op.operationId}`.toLowerCase();if(mode==="catalog"){let n=0;if(isBadCatalogOp(op))n-=500;if(/for.?you|home|recommend|discover|feed/.test(s))n+=140;if(/popular|trending|rank|hot/.test(s))n+=100;if(/dramas|playlets|list|shows|releases|new/.test(s))n+=70;if(/detail|info|episode|chapter/.test(s))n-=40;if(/stream|play|video|vip|premium/.test(s))n-=140;return n}if(mode==="detail"){let n=0;if(/detail|info|series|book|drama|theater/.test(s))n+=120;if(/episode|chapter/.test(s))n-=20;if(/stream|play|video/.test(s))n-=70;return n}if(mode==="episodes"){let n=0;if(/episodes|episode.?list|chapters|chapter.?list|getchapters|playlist/.test(s))n+=150;if(/detail/.test(s))n+=30;if(/stream/.test(s))n-=80;return n}let n=0;if(/stream|play|video/.test(s))n+=140;if(/episode|chapter/.test(s))n+=80;return n}
function preferredIndex(slug:string,mode:ProviderMode,route:string){const list=preferredRoutes(slug,mode);const i=list.indexOf(route);return i<0?Number.MAX_SAFE_INTEGER:i}
function candidateOps(all:Op[],slug:string,name:string,mode:ProviderMode){const preferred=preferredRoutes(slug,mode);const filtered=all.filter((o)=>o.provider===name&&o.method==="GET"&&canAuto(o,mode)&&(mode!=="catalog"||!isBadCatalogOp(o)));return filtered.sort((a,b)=>{const ai=preferredIndex(slug,mode,a.route),bi=preferredIndex(slug,mode,b.route);if(ai!==bi)return ai-bi;const ap=preferred.includes(a.route),bp=preferred.includes(b.route);if(ap!==bp)return ap?-1:1;return score(b,mode)-score(a,mode)})}
function languageFor(op:Op){return /^\/reelshort\//i.test(op.route)?"in":"id"}
function urlFor(op:Op,id?:string,episode?:Episode){let route=op.route;const qs=new URLSearchParams();for(const p of op.parameters){if(p.in==="header")continue;let value=p.defaultValue||"";if(!value&&/^(lang|language|locale)$/i.test(p.name))value=languageFor(op);else if(!value&&/country/i.test(p.name))value="ID";else if(!value&&/^page$/i.test(p.name))value="1";else if(!value&&/offset/i.test(p.name))value="0";else if(!value&&/page.?size|limit|size|count|per.?page/i.test(p.name))value="20";else if(!value&&/^(tabId|tab_id)$/i.test(p.name))value="1";else if(!value&&/^id$/i.test(p.name)&&/\/tabs\//i.test(op.route)&&!id)value="1";else if(/ep|episode|chapter|section/i.test(p.name)&&episode)value=/(?:no|num|number|index)$/i.test(p.name)?String(episode.number):(episode.sourceId||String(episode.number));else if(id&&/id|code|slug|vid|keyword|content|playlet|series|book|fake/i.test(p.name))value=id;if(!value&&!p.required)continue;if(p.in==="path")route=route.replace(`{${p.name}}`,encodeURIComponent(value||"1"));else if(value)qs.set(p.name,value)}route=route.replace(/\{page\?\}/g,"1");return `${route}${qs.size?`?${qs}`:""}`}
async function json(path:string,method="GET"){const r=await providerFetch("captain",path,{method});if(!r.ok)throw new Error(`Captain ${r.status} ${path}`);return r.json()}
function genres(r:Rec){const values:any[]=[];for(const k of["genre","genres","tag","tags","tag_list","tagList","content_tags","categories","theme"]){const v=r[k];if(Array.isArray(v))for(const x of v){if(typeof x==="string")values.push(x);else if(rec(x)){const t=txt(x,["tag_name","tagName","name","title","label","text"]);if(t)values.push(t)}}else if(typeof v==="string")values.push(...v.split(/[,|/]/))}return values.map(String).map(x=>x.trim()).filter(Boolean).slice(0,3).join(" • ")}
function normalizeEpisodes(payload:unknown):Episode[]{const seen=new Set<string>();return episodeObjects(payload).map((r,i)=>{const n=num(r,["episode","episode_no","episodeNo","episodeNumber","ep","index","chapter","chapter_num","chapterNum","chapterIndex","episodeIndex"])||i+1;const sid=txt(r,["id","episodeid","episode_id","episodeId","chapter_id","chapterId","fileId","vid","section_id","sectionId"])||String(n);return{id:sid,sourceId:sid,number:n,title:txt(r,["title","name","episodeTitle","episodeName","chapterName","chapter_title","chapterTitle"])||`Episode ${n}`,streamUrl:stream(r)||undefined}}).filter((e)=>{const k=`${e.sourceId}:${e.number}`;if(seen.has(k))return false;seen.add(k);return true}).sort((a,b)=>a.number-b.number)}
function dramaFrom(r:Rec,slug:string,name:string,episodes:Episode[]=[]):Drama|null{const sourceId=slug==="shortmax"?(txt(r,["code","id"])||rawId(r)):rawId(r),t=title(r);if(!sourceId||!t)return null;const cover=image(r)||"https://placehold.co/720x1280/111111/eeeeee?text=DRACIN";let eps=episodes;if(!eps.length){const samples=normalizeEpisodes(r);if(samples.length)eps=samples;else{const total=num(r,["episodes","episode_count","episodeCount","chapter_num","chapterNum","chapter_count","chapterCount","total_episode","totalEpisode","total_episodes","totalEpisodes","totalEpisodeNum","episodeTotal","read_episode","latestEpisodeNumber"]);if(total>0&&total<=500)eps=Array.from({length:total},(_,i)=>({id:`ep-${i+1}`,sourceId:String(i+1),number:i+1,title:`Episode ${i+1}`}))}}return{id:`${slug}--${sourceId}`,source:"captain",provider:slug,providerName:name,sourceId,title:t,synopsis:txt(r,["synopsis","description","desc","intro","summary","abstract","introduce","special_desc","specialDesc","share_text"])||"Sinopsis belum tersedia.",genre:genres(r)||"Drama",cover,backdrop:cover,episodes:eps}}

async function fetchEpisodesFor(all:Op[],slug:string,name:string,id:string):Promise<Episode[]>{const ops=candidateOps(all,slug,name,"episodes");for(const op of ops.slice(0,8)){try{const payload=await json(urlFor(op,id));const eps=normalizeEpisodes(payload);if(eps.length)return eps}catch{}}return[]}

export async function getProviderCatalog(slug:string):Promise<Drama[]>{const name=providerName(slug);if(!name)return[];try{const all=await operations();const ops=candidateOps(all,slug,name,"catalog");for(const op of ops.slice(0,10)){try{const payload=await json(urlFor(op));const seen=new Set<string>();const items=objects(payload).map((r)=>dramaFrom(r,slug,name)).filter((x):x is Drama=>!!x).filter((x)=>!seen.has(x.id)&&!!seen.add(x.id));if(items.length)return items.slice(0,40)}catch{}}return[]}catch(e){console.error(`DRACIN ${name} catalog failed`,e);return[]}}

export async function getProviderDrama(fullId:string):Promise<Drama|null>{const split=fullId.indexOf("--");if(split<1)return null;const slug=fullId.slice(0,split),id=fullId.slice(split+2),name=providerName(slug);if(!name||slug==="freereels")return null;try{const all=await operations();const ops=candidateOps(all,slug,name,"detail");for(const op of ops.slice(0,10)){try{const payload=await json(urlFor(op,id));const detail=(objects(payload)[0]||(rec(payload)?payload:null));if(!detail)continue;let eps=normalizeEpisodes(payload);const fullEpisodes=await fetchEpisodesFor(all,slug,name,id);if(fullEpisodes.length>eps.length)eps=fullEpisodes;const d=dramaFrom({...detail,id:rawId(detail)||id},slug,name,eps);if(d){if(d.episodes.length)return d;const catalog=await getProviderCatalog(slug);const base=catalog.find((item)=>item.sourceId===id);if(base?.episodes.length)return{...d,episodes:base.episodes};return d}}catch{}}const catalog=await getProviderCatalog(slug);const base=catalog.find((d)=>d.sourceId===id)||null;if(!base)return null;const fullEpisodes=await fetchEpisodesFor(all,slug,name,id);return fullEpisodes.length?{...base,episodes:fullEpisodes}:base}catch{return null}}

export async function getProviderEpisodeStream(drama:Drama,episode:Episode):Promise<string|null>{if(episode.streamUrl)return episode.streamUrl;const name=drama.providerName||providerName(drama.provider);if(!name||drama.provider==="freereels")return null;try{const all=await operations();const ops=candidateOps(all,drama.provider,name,"play");for(const op of ops.slice(0,10)){try{const payload=await json(urlFor(op,drama.sourceId,episode));const s=stream(payload);if(s)return s}catch{}}return null}catch{return null}}
