import { providerFetch } from "@/lib/providers";
import type { Drama, Episode } from "@/lib/dramas";

type Rec = Record<string, any>;
type Op = { method:string; route:string; provider:string; summary:string; operationId:string; parameters:{name:string;in:string;required:boolean}[] };

export const CAPTAIN_PROVIDERS = [
  "Anichin","BiliTV","BonusTV","CashDrama","CubeTV","DotDrama","DramaBite","DramaBox Baru","DramaNova","DramaPops","DramaRush","FlareFlow","FlexTV","FlickReels","FreeReels","LuminaReels","MeloShort","Melolo","MicroDrama","MoboReels","MovieBox","NetShort","Playlet","RadReels","RapidTV","RaptDrama","ReelBuzz","ReelShort","Sereal","ShortBox","ShortMax","ShortSky","ShortWave","Shorten","ShotShort","SnackShort","SodaReels","StarShort","StardustTV","Vigloo","WeTV","iDrama"
] as const;

export function providerSlug(name:string){return name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
export function providerName(slug:string){return CAPTAIN_PROVIDERS.find((p)=>providerSlug(p)===slug) || null}

let cached:{at:number;ops:Op[]}|null=null;
function embeddedSpec(html:string):Rec|null{for(const marker of["openapi","swagger"]){let cursor=0;while((cursor=html.indexOf(`\"${marker}\"`,cursor))!==-1){const start=html.lastIndexOf("{",cursor);if(start<0)break;let depth=0,quoted=false,escaped=false;for(let i=start;i<html.length;i++){const ch=html[i];if(quoted){if(escaped)escaped=false;else if(ch==="\\")escaped=true;else if(ch==='"')quoted=false;continue}if(ch==='"')quoted=true;else if(ch==="{")depth++;else if(ch==="}"&&--depth===0){try{const parsed=JSON.parse(html.slice(start,i+1));if(parsed?.paths)return parsed}catch{}break}}cursor+=marker.length+2}}return null}
async function operations():Promise<Op[]>{if(cached&&Date.now()-cached.at<3600000)return cached.ops;let spec:Rec|null=null;for(const path of["/openapi.json","/swagger.json","/swagger/v1/swagger.json","/api-docs"]){try{const r=await providerFetch("captain",path);if(r.ok){const j=await r.json();if(j?.paths){spec=j;break}}}catch{}}if(!spec){const r=await providerFetch("captain","/swagger");if(!r.ok)throw new Error(`Swagger ${r.status}`);spec=embeddedSpec(await r.text())}if(!spec)throw new Error("Captain OpenAPI unavailable");const ops:Op[]=[];for(const[route,item]of Object.entries<any>(spec.paths||{})){for(const method of["get","post"]){const op=item?.[method];if(!op)continue;const summary=op.summary||"",operationId=op.operationId||`${method} ${route}`;if(/unlock|bypass|decrypt|paywall/i.test(`${route} ${summary} ${operationId}`))continue;for(const provider of op.tags||[]){ops.push({method:method.toUpperCase(),route,provider,summary,operationId,parameters:[...(item.parameters||[]),...(op.parameters||[])].map((p:any)=>({name:p.name,in:p.in,required:!!p.required}))})}}}cached={at:Date.now(),ops};return ops}

function rec(v:unknown):v is Rec{return !!v&&typeof v==="object"&&!Array.isArray(v)}
function txt(r:Rec,keys:string[]){for(const k of keys){const v=r[k];if(typeof v==="string"&&v.trim())return v.trim();if(typeof v==="number")return String(v)}return""}
function num(r:Rec,keys:string[]){for(const k of keys){const n=Number(r[k]);if(Number.isFinite(n)&&n>0)return n}return 0}
function rawId(r:Rec){return txt(r,["key","id","drama_id","dramaId","book_id","bookId","series_id","seriesId","series_key","seriesKey","playlet_id","playletId","videoid","videoId","vid","contentId","subjectId","code","slug"])}
function title(r:Rec){return txt(r,["title","name","drama_name","dramaName","book_name","bookName","series_name","seriesName","short_play_name","shortPlayName","videoName","contentName"])}
function image(r:Rec,depth=0):string{if(depth>4)return"";const direct=txt(r,["cover","cover_url","coverUrl","poster","poster_url","posterUrl","image","image_url","imageUrl","thumb","thumbnail","verticalCover","bookCover"]);if(/^https?:\/\//i.test(direct))return direct;for(const v of Object.values(r)){if(rec(v)){const x=image(v,depth+1);if(x)return x}}return""}
function objects(v:unknown,depth=0):Rec[]{if(depth>7)return[];if(Array.isArray(v)){const d=v.filter(rec).filter((x)=>rawId(x)&&title(x));if(d.length)return d;return v.flatMap((x)=>objects(x,depth+1))}if(rec(v)){for(const k of["items","list","data","dramas","results","records","content","rows","videos","books","recommendations"]){if(k in v){const f=objects(v[k],depth+1);if(f.length)return f}}return Object.values(v).flatMap((x)=>objects(x,depth+1))}return[]}
function episodeObjects(v:unknown,depth=0):Rec[]{if(depth>7)return[];if(Array.isArray(v)){const rs=v.filter(rec);const eps=rs.filter((r)=>num(r,["episode","episode_no","episodeNo","ep","index","chapter","chapterIndex","episodeIndex"])||txt(r,["episode_id","episodeId","chapter_id","chapterId","fileId"]));if(eps.length)return eps;return v.flatMap((x)=>episodeObjects(x,depth+1))}if(rec(v)){for(const k of["episodes","episode_list","episodeList","chapters","chapterList","chapter_list","videoList","videos","list","items","data"]){if(k in v){const f=episodeObjects(v[k],depth+1);if(f.length)return f}}return Object.values(v).flatMap((x)=>episodeObjects(x,depth+1))}return[]}
function stream(v:unknown,depth=0):string{if(depth>8)return"";if(typeof v==="string"&&/^https?:\/\//i.test(v)&&/(\.m3u8|\.mp4|stream|video)/i.test(v))return v;if(Array.isArray(v)){for(const x of v){const s=stream(x,depth+1);if(s)return s}}else if(rec(v)){for(const k of["external_audio_h264_m3u8","m3u8_url","m3u8Url","m3u8","video_url","videoUrl","play_url","playUrl","stream_url","streamUrl","url"]){const s=stream(v[k],depth+1);if(s)return s}for(const x of Object.values(v)){const s=stream(x,depth+1);if(s)return s}}return""}

function canAuto(op:Op,mode:"catalog"|"detail"|"play"){const req=op.parameters.filter((p)=>p.required&&p.in!=="header");if(mode==="catalog")return req.length===0;if(mode==="detail")return req.length>=1&&req.length<=2&&req.every((p)=>/id|code|slug|vid|keyword|content/i.test(p.name));return req.length>=1&&req.length<=3&&req.every((p)=>/id|code|slug|vid|ep|episode|chapter|section|content/i.test(p.name))}
function score(op:Op,mode:"catalog"|"detail"|"play"){const s=`${op.route} ${op.summary}`.toLowerCase();if(mode==="catalog"){let n=0;if(/home|for.?you|recommend/.test(s))n+=100;if(/popular|trending|rank/.test(s))n+=80;if(/dramas|list|shows|releases|new/.test(s))n+=50;if(/stream|play|video|vip|premium/.test(s))n-=120;return n}if(mode==="detail"){let n=0;if(/detail|info/.test(s))n+=100;if(/episode|chapter/.test(s))n+=50;if(/stream|play|video/.test(s))n-=50;return n}let n=0;if(/stream|play|video|episode/.test(s))n+=100;return n}
function urlFor(op:Op,id?:string,episode?:Episode){let route=op.route;const qs=new URLSearchParams();for(const p of op.parameters){if(p.in==="header")continue;let value="";if(/lang$/i.test(p.name))value="id-ID";else if(/country/i.test(p.name))value="ID";else if(/page$/i.test(p.name))value="1";else if(/limit|size|count|perpage/i.test(p.name))value="20";else if(/ep|episode|chapter|section/i.test(p.name)&&episode)value=episode.sourceId||String(episode.number);else if(id&&/id|code|slug|vid|keyword|content/i.test(p.name))value=id;if(!value&&!p.required)continue;if(p.in==="path")route=route.replace(`{${p.name}}`,encodeURIComponent(value||"1"));else if(value)qs.set(p.name,value)}return `${route}${qs.size?`?${qs}`:""}`}
async function json(path:string,method="GET"){const r=await providerFetch("captain",path,{method});if(!r.ok)throw new Error(`Captain ${r.status} ${path}`);return r.json()}
function dramaFrom(r:Rec,slug:string,name:string,episodes:Episode[]=[]):Drama|null{const sourceId=rawId(r),t=title(r);if(!sourceId||!t)return null;const cover=image(r)||"https://placehold.co/720x1280/111111/eeeeee?text=DRACIN";return{id:`${slug}--${sourceId}`,source:"captain",provider:slug,providerName:name,sourceId,title:t,synopsis:txt(r,["synopsis","description","desc","intro","summary","abstract"])||"Sinopsis belum tersedia.",genre:"Drama",cover,backdrop:cover,episodes}}

export async function getProviderCatalog(slug:string):Promise<Drama[]>{const name=providerName(slug);if(!name)return[];try{const ops=(await operations()).filter((o)=>o.provider===name&&o.method==="GET"&&canAuto(o,"catalog")).sort((a,b)=>score(b,"catalog")-score(a,"catalog"));for(const op of ops.slice(0,5)){try{const payload=await json(urlFor(op));const seen=new Set<string>();const items=objects(payload).map((r)=>dramaFrom(r,slug,name)).filter((x):x is Drama=>!!x).filter((x)=>!seen.has(x.id)&&!!seen.add(x.id));if(items.length)return items.slice(0,40)}catch{}}return[]}catch(e){console.error(`DRACIN ${name} catalog failed`,e);return[]}}

export async function getProviderDrama(fullId:string):Promise<Drama|null>{const split=fullId.indexOf("--");if(split<1)return null;const slug=fullId.slice(0,split),id=fullId.slice(split+2),name=providerName(slug);if(!name||slug==="freereels")return null;try{const ops=(await operations()).filter((o)=>o.provider===name&&o.method==="GET"&&canAuto(o,"detail")).sort((a,b)=>score(b,"detail")-score(a,"detail"));for(const op of ops.slice(0,6)){try{const payload=await json(urlFor(op,id));const detail=(objects(payload)[0]||(rec(payload)?payload:null));if(!detail)continue;const eps=episodeObjects(payload).map((r,i)=>{const n=num(r,["episode","episode_no","episodeNo","ep","index","chapter","chapterIndex","episodeIndex"])||i+1;const sid=txt(r,["id","episode_id","episodeId","chapter_id","chapterId","fileId","vid"])||String(n);return{id:sid,sourceId:sid,number:n,title:txt(r,["title","name","episodeName","chapterName"])||`Episode ${n}`,streamUrl:stream(r)||undefined}}).sort((a,b)=>a.number-b.number);const d=dramaFrom({...detail,id:rawId(detail)||id},slug,name,eps);if(d)return d}catch{}}const catalog=await getProviderCatalog(slug);return catalog.find((d)=>d.sourceId===id)||null}catch{return null}}

export async function getProviderEpisodeStream(drama:Drama,episode:Episode):Promise<string|null>{if(episode.streamUrl)return episode.streamUrl;const name=drama.providerName||providerName(drama.provider);if(!name||drama.provider==="freereels")return null;try{const ops=(await operations()).filter((o)=>o.provider===name&&o.method==="GET"&&canAuto(o,"play")).sort((a,b)=>score(b,"play")-score(a,"play"));for(const op of ops.slice(0,8)){try{const payload=await json(urlFor(op,drama.sourceId,episode));const s=stream(payload);if(s)return s}catch{}}return null}catch{return null}}
